export const LAYERS = [
  {id:'knit',name:'Cut-resistant knit',title:'The foundation.',material:'UHMWPE + elastane look',build:'Thin, athletic full-body knit',attachment:'Sewn sleeves carry the limb mounts.',description:'A close-fitting black base layer with a soft turtleneck extending to just beneath the jaw. The face stays open.',note:'The collar knit covers the hidden neck armor. Plates attach through dedicated sleeves and hardware, never directly to the stretch knit.',focus:[0,1.43,0],distance:1.5},
  {id:'pads',name:'Impact pads',title:'Quiet impact protection.',material:'Ghost-style low-profile pad concept',build:'Shoulders · elbows · knees · hips',attachment:'Captured inside dedicated garment pockets.',description:'Flexible dark pads follow the joints without changing the silhouette. A thin optional trauma pad sits behind the chest.',note:'Pads are revealed in this layer view and remain concealed in the assembled suit.',focus:[.3,1.47,.01],distance:1.2},
  {id:'ballistic',name:'Soft ballistic vest',title:'Close to the body.',material:'Concealable Level IIIA design target',build:'Approx. 5 mm visual thickness',attachment:'Continuous front, back, and side coverage.',description:'A thin, flexible torso wrap sits beneath the rigid stab panels. Its independent construction preserves the two-vest stack.',note:'Level IIIA is a specification target, not a performance claim for this model or the assembled system.',focus:[0,1.43,0],distance:1.45},
  {id:'stab',name:'Rigid stab vest',title:'A separate hard barrier.',material:'Carbon-composite panel concept',build:'Vital torso coverage only',attachment:'Independent vest over the soft ballistic layer.',description:'Thin rigid panels face outward over the soft vest, covering the vital front, back, and sides of the torso.',note:'The stab vest ends below the neck. The concealed throat collar is a separate component.',focus:[0,1.44,0],distance:1.4},
  {id:'neck',name:'Concealed neck armor',title:'Hidden beneath the knit.',material:'Three overlapping rigid lames',build:'Front and sides · open nape',attachment:'Hidden pocket on the inner face of the turtleneck.',description:'A separate low collar wraps the throat beneath the soft turtleneck. The opening at the nape preserves space to look up.',note:'Intended as a stab/slash design layer, not a helmet. The knit fades in inspection so the concealed lames can be seen.',focus:[0,1.755,0],distance:.8},
  {id:'harness',name:'Webbing harness',title:'The load path.',material:'25 mm black nylon webbing',build:'Independent over-vest harness',attachment:'Straps through plate slots · side-release buckles.',description:'A dedicated harness carries the torso plates over both vests. It wraps the shoulders, ribs, and back without replacing either protective layer.',note:'Two inner elastic strips support the abdominal lames. Slotted rivets allow 8–15 mm of intended sliding travel.',focus:[0,1.38,0],distance:1.35},
  {id:'plates',name:'Articulated outer plates',title:'Hard shell. Soft joints.',material:'Graphene-enhanced polymer concept',build:'Dark Nanovate-style electroplated finish',attachment:'Torso: harness slots. Limbs: hook-and-loop sleeves.',description:'A single chest plate ends at the solar plexus. Four separate abdominal lames overlap downward, with a 40 mm fabric gap above the belt.',note:'Shoulders, outer forearms, thighs, shins, and upper back stay separate. Each 40–70 mm abdominal lame overlaps 10–20 mm; no rigid plate crosses the waist.',focus:[0,1.39,0],distance:1.5},
  {id:'finish',name:'Gloves & boots',title:'A grounded finish.',material:'Matte black stretch and rubber',build:'Athletic boots · full-finger gloves',attachment:'Independent wearable accessories.',description:'Low-profile black gloves and athletic boots complete the suit. Flexible transitions at the wrists and ankles maintain the continuous silhouette.',note:'No weapons. No cape. An original protective-wear study.',focus:[.12,.22,.05],distance:1.1}
];
