export const LAYERS = [
  {id:'knit',name:'Cut-resistant knit',title:'The foundation.',material:'UHMWPE + elastane look',build:'Thin, athletic full-body knit',attachment:'Sewn sleeves carry the limb mounts.',description:'A close-fitting black base layer with a soft turtleneck extending to just beneath the jaw. The face stays open.',note:'The collar knit covers the hidden neck armor. Plates attach through dedicated sleeves and hardware, never directly to the stretch knit.',focus:[0,1.43,0],distance:1.5},
  {id:'pads',name:'Impact pads',title:'Low-profile impact pads.',material:'D3O Ghost product references',build:'Shoulders · chest · back · elbows · knees · insteps',attachment:'Removable inserts in external pockets sewn into the Cutlon garment.',description:'Ten Ghost inserts occupy external Cutlon pockets: paired shoulders, elbows, knees and insteps, plus chest and back.',note:'Pads are revealed in this layer view and remain concealed in the assembled suit. No hip pads are included.',focus:[0,1.43,0],distance:1.6},
  {id:'ballistic',name:'Soft ballistic vest',title:'Close to the body.',material:'Safe Life Defense HYPERLINE HL.HG2 reference',build:'4.83 mm armor · 0.76 mm carrier',attachment:'Continuous front, back, and side coverage.',description:'A thin, flexible torso wrap sits beneath the rigid stab panels. Its independent construction preserves the two-vest stack.',note:'Level IIIA is a specification target, not a performance claim for this model or the assembled system.',focus:[0,1.43,0],distance:1.45},
  {id:'stab',name:'Rigid stab vest',title:'A separate hard barrier.',material:'Carbon-composite panel concept',build:'Front · back · left flank',attachment:'Independent vest over the soft ballistic layer.',description:'Thin rigid panels follow the vital front and back of the torso. A fitted left flank remains; the right rigid flank has been removed.',note:'The stab vest ends below the neck. The concealed throat collar is a separate component.',focus:[0,1.44,0],distance:1.4},
  {id:'neck',name:'Concealed neck armor',title:'Hidden beneath the knit.',material:'Three overlapping rigid lames',build:'Front and sides · open nape',attachment:'Hidden pocket on the inner face of the turtleneck.',description:'A separate low collar wraps the throat beneath the soft turtleneck. The opening at the nape preserves space to look up.',note:'Intended as a stab/slash design layer, not a helmet. The knit fades in inspection so the concealed lames can be seen.',focus:[0,1.755,0],distance:.8},
  {id:'harness',name:'Webbing harness',title:'Continuous support.',material:'25 mm torso webbing · narrow limb loops',build:'Chest and rib wraps · shoulder paths · limb loops',attachment:'Straps through plate slots · side-release buckles.',description:'Complete straps encircle the chest, ribs and limbs. Flat shoulder paths join the front and back. Internal suspension tabs and separate soft leg loops support the floating groin pouch; there is no waist belt.',note:'Two inner elastic strips support the abdominal lames. Slotted rivets allow 8–15 mm of intended sliding travel.',focus:[0,1.38,0],distance:1.35},
  {id:'plates',name:'Articulated outer plates',title:'Contoured for close wear.',material:'Graphene-enhanced polymer concept',build:'Chrome Nanovate-style electroplated finish',attachment:'Torso: harness slots. Limbs: hook-and-loop sleeves.',description:'Slimmer muscle-contoured shells follow the body, including new biceps and rear-thigh coverage. A single chest plate ends at the solar plexus. Four independent abdominal lames leave the waist soft. A removable groin cup sits separately below them.',note:'Nineteen independent outer components include the groin insert. Joints remain flexible; no rigid plate bridges the waist. Fit and trauma reduction are not established by this visualization.',focus:[0,1.39,0],distance:1.5},
  {id:'finish',name:'Gloves & boots',title:'A grounded finish.',material:'Black mesh, leather-look panels and rubber',build:'Athletic boots · NETFORCE G.I.E glove reference',attachment:'Independent wearable accessories.',description:'The gloves reference the NETFORCE G.I.E exterior: extended cuffs, mesh knuckle panels and dorsal finger inserts. Athletic black boots complete the suit. Flexible transitions at the wrists and ankles maintain the continuous silhouette.',note:'Gloves are a visual approximation of the referenced commercial product, not a manufacturer CAD model. Reference: <a href="https://netforce-defense.com/" target="_blank" rel="noopener noreferrer">NETFORCE</a>.',focus:[.12,.22,.05],distance:1.1}
];
