const source=(name,url)=>({name,url});
const d3o=slug=>source('D3O product & datasheet','https://www.d3o.com/partners/solutions/molded-parts/'+slug+'/');
const chest=d3o('d3o-ghost-chest-protector'),back=d3o('d3o-ghost-back-protector'),limb=d3o('d3o-ghost-l2-limb-protectors'),met=d3o('d3o-ghost-met-guards');
const ng=source('NG Ballistics','https://ngballistics.com/');
const adept=slug=>source('Adept product reference','https://www.ade.pt/product/'+slug+'/');
const torso=adept('novasteel-breastplate'),shoulders=adept('shoulder-armor-plates'),helmet=adept('novasteel-helmet-high-cut'),mandible=adept('ballistic-face-shield'),buckler=adept('ballistic-buckler'),netforce=source('NETFORCE G.I.E','https://netforce-defense.com/');
export const PRODUCTS=[
 {name:'Cutlon garment',features:['Cut-, tear- and abrasion-resistant fabric reference','External D3O pockets with flatlock seams','Garment stays fixed when other components separate'],dimensions:'Custom garment; model bounds shown per component',contribution:'Cut-resistant foundation and removable impact-pad pockets.',sources:[source('Cutlon','https://cutlon.com/features/')]},
 {name:'D3O Ghost system',features:['Ghost chest and back: CE Level 1 products','Ghost L2 shoulder, elbow and knee inserts','LP met guards inside the footwear'],dimensions:'6–11 mm, depending on the selected product',contribution:'Flexible impact inserts, independently visible beneath the armor.',sources:[chest,back,limb,met]},
 {name:'NovaSteel breastplate set',features:['Separate stamped front and back steel shells','Manufacturer lists IIIA handgun and knife/spike resistance','Integral suspension straps; RF1 upgrade is not included'],dimensions:'L/XL reference: 350 × 432 mm; shell under 2.54 mm. Fitted mesh is approximate.',contribution:'Replaces both torso vests and the former chest, back and abdominal shells.',sources:[torso,source('Operator guide','https://www.ade.pt/wp-content/uploads/2024/05/Breastplate_guide.pdf')]},
 {name:'NovaSteel shoulder plates',features:['Multi-curved NovaSteel with stamped channels','Manufacturer lists VPAM-3 and knife/spike resistance','Floating strap suspension above the D3O shoulder pockets'],dimensions:'Published thickness: under 2.54 mm; 0.9 lb per plate. Outline dimensions are not published.',contribution:'Independent shoulder armor over the impact inserts.',sources:[shoulders]},
 {name:'Concealed neck lames',features:['Three overlapping curved lames','Covered by the Cutlon turtleneck','Open nape; independent of torso and helmet'],dimensions:'35 mm lame height • custom geometry',contribution:'Concept throat coverage beneath the fabric collar.',sources:[source('Cutlon pocket fabric','https://cutlon.com/features/')]},
 {name:'Straps and soft carriers',features:['NovaSteel shoulder and complete torso straps','Independent sleeve mounts and groin suspension','No waist belt or abdominal tracks'],dimensions:'Model webbing: 25 mm torso / 18 mm limb loops',contribution:'Supports independent armor pieces and the removable groin insert.',sources:[torso]},
 {name:'Anatomically fitted limb shells',features:['Tapered, rounded shells follow each limb section','Recessed edges and separate sleeve mounts','Gaps at the wrists, elbows, knees and hip creases'],dimensions:'Custom shell thickness: 2.4 mm; per-piece bounds below',contribution:'Close-fitting outer coverage; actual concealment and range of motion require a wearer fitting.',sources:[ng,source('Nanovate coating reference','https://www.integran.com/structural-hybrid-components')]},
 {name:'NETFORCE G.I.E / athletic boots',features:['G.I.E integrates a contact electroshock function','Rechargeable battery system; manufacturer lists USB-C charging','Separate athletic boots around D3O met guards'],dimensions:'Custom exterior approximation; electronics are not modeled internally',contribution:'Referenced electric-impulse gloves and independent protective footwear.',sources:[netforce,met]},
 {name:'NovaSteel helmet and flip mandible',features:['High-cut steel helmet; manufacturer lists VPAM-3','Solid Gen 2 flip mandible with an open eye gap','Mandible uses its own dedicated welded circlet'],dimensions:'Helmet sizes M/L; face module 0.79 lb. Mesh dimensions are approximate.',contribution:'Head and lower-face coverage as separate inspectable components.',sources:[helmet,mandible]},
 {name:'NovaSteel ballistic buckler',features:['Faceted steel shield with a raised central boss','Manufacturer-listed IIIA / VPAM-3','Ambidextrous central handle; separate from the forearm plate'],dimensions:'12.2 in / 310 mm nominal diameter; outline modeled from photos',contribution:'Hand-held shield coverage, carried independently of the suit.',sources:[buckler]}
];
export const GHOST_PRODUCTS={
 chest:{name:'D3O Ghost Chest — full',features:['CE Level 1 • EN 1621-3:2018','Winged rib coverage and open triangular geometry','Lycra backing faces the body; removable pocket insert'],dimensions:'335 × 245 × 8.25 mm • published flat size',contribution:'Impact absorption across the chest and adjoining ribs.',sources:[chest]},
 back:{name:'D3O Ghost Back — M',features:['CE Level 1 • EN 1621-2:2014','Open lattice with a tapered lower extension','Fabric backing toward the body; external Cutlon pocket'],dimensions:'262 × 404 × 8 mm • published size M',contribution:'Flexible impact coverage along the back.',sources:[back]},
 shoulder:{name:'D3O Ghost L2 — shoulder',features:['CE Level 2 • EN 1621-1:2012, Type A','Tapered triangular cells on stretch fabric','Removable external Cutlon shoulder pocket'],dimensions:'193 × 154 × 11 mm • published flat size',contribution:'Impact absorption over the shoulder joint.',sources:[limb]},
 limb:{name:'D3O Ghost L2 — knee / elbow',features:['CE Level 2 • EN 1621-1:2012, Type A','Long tapered outline with articulation notches','Removable external Cutlon joint pocket'],dimensions:'240 × 147 × 11 mm • published flat size',contribution:'Impact coverage around the elbow or knee.',sources:[limb]},
 met:{name:'D3O Ghost Met Guard — LP M',features:['Segmented triangles conform over the instep','Fabric-backed insert in the Cutlon foot pocket','Performance depends on the complete boot construction'],dimensions:'134 × 108 × 6 mm • published LP size M',contribution:'Metatarsal impact protection over the top of the foot.',sources:[met]}
};
function modelDimensions(component){return component.dimensions?component.dimensions.map(v=>Math.round(v*1000)).join(' × ')+' mm • model bounds (W × H × D)':'Custom dimensions';}
export function componentProduct(component){
 const n=component.name.toLowerCase(),base=PRODUCTS[component.layer],ghost=component.meshes.find(m=>m.userData.ghostKind)?.userData.ghostKind;
 if(ghost){const product={...GHOST_PRODUCTS[ghost]};if(n.includes('elbow'))product.contribution='Impact absorption at the elbow, with the long insert following the arm.';if(n.includes('knee'))product.contribution='Impact absorption around the knee, with a tapered lower extension.';return product;}
 if(component.id==='groin-cup')return {name:'Removable groin cup — concept',features:['Curved insert in a soft textile envelope','Separate from the torso shell','Custom, unrated component'],dimensions:modelDimensions(component),contribution:'Concept impact coverage at the groin without bridging the waist.',sources:[]};
 if(component.id==='groin-pouch'||component.id==='groin-support')return {name:'Floating groin carrier',features:['Flexible cut-resistant pouch','Internal harness tabs and soft leg loops','Removable insert; no waist belt'],dimensions:modelDimensions(component),contribution:'Holds the separate groin insert while allowing hip movement.',sources:[PRODUCTS[0].sources[0]]};
 if(component.layer===6&&/biceps|hamstring|forearm|thigh|shin/.test(n))return {name:'NG Ballistics material reference',features:['Local limb contours with a tapered, rounded perimeter','Independent sleeve mount; 2.4 mm visual shell','Joint clearances are modeled; wearer mobility is unverified'],dimensions:modelDimensions(component),contribution:n.includes('hamstring')?'Adds rear-thigh shell coverage while leaving the knee crease free.':n.includes('biceps')?'Adds upper-arm shell coverage without joining the shoulder or elbow.':n.includes('thigh')?'Adds fitted shell coverage over the quadriceps.':n.includes('shin')?'Adds a contoured shell along the front of the lower leg.':'Adds a fitted outer-forearm shell with a flexible wrist transition.',sources:PRODUCTS[6].sources};
 if(component.layer===7&&n.includes('boot'))return {name:'Athletic boot — custom fit',features:['Closed heel and shaped traction sole','Cross laces and flexible ankle collar','D3O met insert housed beneath the upper'],dimensions:modelDimensions(component),contribution:'Footwear around the concealed instep protector.',sources:[met]};
 if(component.id.startsWith('novasteel-')){
  const product=component.id==='novasteel-carrier'?PRODUCTS[5]:component.id.includes('shoulder')?PRODUCTS[3]:component.id==='novasteel-buckler'?PRODUCTS[9]:component.id==='novasteel-front'||component.id==='novasteel-back'?PRODUCTS[2]:PRODUCTS[8];
  if(component.id==='novasteel-mandible')return {name:'NovaSteel Flip Mandible — Gen 2',features:['Solid steel lower-face guard with an open eye gap','Manufacturer lists 9 mm FMJ at 1,400 fps','Flip mechanism requires the supplied dedicated circlet'],dimensions:'0.79 lb published module weight; '+modelDimensions(component),contribution:'Adds lower-face coverage; modeled separately from the helmet.',sources:[mandible]};
  if(component.id==='novasteel-circlet')return {name:'Dedicated welded flip circlet',features:['Supplied as part of the Gen 2 mandible set','Dedicated sealed pivots leave the side rails free','Standard circlet variants do not accept this mandible'],dimensions:modelDimensions(component),contribution:'Connects the flip mandible to the compatible helmet.',sources:[mandible]};
  if(component.id==='novasteel-helmet')return {name:'NovaSteel high-cut helmet',features:['NovaSteel alloy; manufacturer-listed VPAM-3','High-cut rim with suspension and chin retention','2024-and-newer shells accept the linked flip-mandible set'],dimensions:'Published sizes M/L; '+modelDimensions(component),contribution:'Head coverage with a separate facial-protection module.',sources:[helmet,mandible]};
  return {...product,name:component.name,dimensions:product.dimensions+' '+modelDimensions(component)};
 }
 if(component.layer===7&&n.includes('glove'))return {name:'NETFORCE G.I.E electric-impulse glove',features:['Integrated contact electroshock / electric-impulse function','Rechargeable battery: manufacturer lists 1,800 mAh and USB-C','Cut-resistant glove exterior with extended cuff'],dimensions:modelDimensions(component)+'; electronics layout is not specified',contribution:'Hand coverage plus the referenced commercial contact electric-impulse function.',sources:[netforce]};
 return {...base,dimensions:component.layer===5?base.dimensions:modelDimensions(component)};
}
