// Product descriptions are references; bespoke coverage, fit and ratings are not certified by this viewer.
const source=(name,url)=>({name,url});
export const PRODUCTS=[
 {name:'Cutlon fabric reference',features:['Blade-cut resistance','Tear resistance','Abrasion resistance','Thin, flexible textile construction'],sources:[source('Cutlon features','https://cutlon.com/features/')],note:'The full-body garment and collar are custom design features, not an off-the-shelf certified Cutlon suit.'},
 {name:'D3O impact protection reference',features:['Impact-absorbing material family','Flexible protection designed for comfort','Separate pads for shoulders, chest, back, elbows and knees','Removable garment-pocket installation in this concept'],sources:[source('D3O motorcycle protection','https://www.d3o.com/sectors/motorcycle/')],note:'D3O products have model-specific ratings. This custom pad layout does not inherit a product certification; torso pads are not assumed to be Ghost limb inserts.'},
 {name:'Hyperline-style soft vest target',features:['Flexible concealable torso layer','Front, back and side coverage in this concept','Approx. 5 mm thickness from the design brief','Level IIIA is a requested specification target'],sources:[],note:'Current Hyperline manufacturer specifications could not be retrieved. These are brief-specified targets, not verified product ratings.'},
 {name:'PPSS carbon-composite reference',features:['Carbon-fibre composite construction','Manufacturer offers covert vest configurations','Manufacturer range addresses knife, spike and blunt-force threats','Separate from the soft ballistic vest'],sources:[source('PPSS product range','https://www.ppss-group.com/stab-vests/')],note:'PPSS certifications apply to the manufacturer’s tested products. Removing a flank or changing panels creates a custom concept, not a certified PPSS vest.'},
 {name:'Custom concealed neck collar',features:['Three overlapping lames','Hidden underneath the Cutlon turtleneck','Open nape to preserve head movement','Independent from the torso vest'],sources:[],note:'Custom design concept; no tested protection rating is assigned.'},
 {name:'Custom low-profile harness',features:['Continuous chest and rib wrap straps','Flat shoulder straps join front to back','Complete limb attachment loops','No waist belt; groin support uses separate soft loops'],sources:[],note:'The harness carries the shells and keeps them independent from the stretch garment.'},
 {name:'Nanovate-plated polymer concept',features:['Nanovate NP is a nanocrystalline metal coating for polymer substrates','Manufacturer describes compatibility with multiple plastics and additive processes','Chrome appearance requested for this concept','Thin contoured shells with independent sliding abdominal lames'],sources:[source('Integran structural hybrids','https://www.integran.com/structural-hybrid-components')],note:'Coating choice and the graphene-polymer shell are design targets. Chrome appearance alone does not establish impact, stab or ballistic performance.'},
 {name:'NETFORCE glove / athletic boot references',features:['Glove exterior: extended cuff and mesh knuckle area','Dorsal finger inserts and separate finger articulation','Independent wrist and ankle transitions','Closed boot upper, shaped sole and traction detail'],sources:[source('NETFORCE G.I.E','https://netforce-defense.com/')],note:'The glove exterior is a visual approximation. The boots are a custom visual concept with no product rating.'}
];
export function componentProduct(component){
 const base=PRODUCTS[component.layer];const n=component.name.toLowerCase();
 if(component.id==='groin-cup')return {name:'Removable groin impact-cup concept',features:['Curved insert independent from the abdominal armor','Removable from a flexible textile envelope','Soft leg loops and internal suspension tabs','No rigid bridge across the waist or hip crease'],sources:[],note:'Unrated concept. A suitable tested insert and professional fit assessment would be required for real protective use.'};
 if(component.id==='groin-pouch'||component.id==='groin-support')return {name:'Floating groin carrier concept',features:['Soft cut-resistant envelope','Separate pocket for a removable impact cup','Suspended from the internal harness','Flexible leg loops; no waist belt'],sources:[],note:'Custom coverage concept; no ballistic or stab rating is assigned.'};
 if(component.layer===7&&n.includes('boot'))return {name:'Custom athletic boot concept',features:['Closed heel and toe geometry','Low-profile flexible ankle transition','Independent sole and traction lugs','Cross lacing and eyelets'],sources:[],note:'Visual boot design, not a certified protective-footwear product.'};
 let features=[...base.features];
 if(n.includes('biceps'))features.unshift('Body-following upper-arm shell; elbow crease remains flexible');
 if(n.includes('hamstring'))features.unshift('Rear-thigh coverage stops above the back of the knee');
 if(n.includes('abdominal'))features.unshift('Slides independently; soft waist remains unplated');
 return {...base,features};
}
