const source=(name,url)=>({name,url});
const d3o=slug=>source('D3O product & datasheet','https://www.d3o.com/partners/solutions/molded-parts/'+slug+'/');
const chest=d3o('d3o-ghost-chest-protector'),back=d3o('d3o-ghost-back-protector'),limb=d3o('d3o-ghost-l2-limb-protectors'),met=d3o('d3o-ghost-met-guards');
const ng=source('NG Ballistics','https://ngballistics.com/');
export const PRODUCTS=[
 {name:'Cutlon garment',features:['Cut-, tear- and abrasion-resistant fabric reference','External insert pockets with flatlock seams','Base garment and pockets stay on the mannequin'],dimensions:'Custom garment; model bounds shown per component',contribution:'Cut-resistant foundation and a stable carrier for the D3O inserts.',sources:[source('Cutlon','https://cutlon.com/features/')]},
 {name:'D3O Ghost system',features:['Ghost chest and back: CE Level 1 products','Ghost L2 shoulder, elbow and knee inserts','LP met guards inside the footwear'],dimensions:'6–11 mm, depending on the selected product',contribution:'Flexible impact-absorbing inserts in external Cutlon pockets.',sources:[chest,back,limb,met]},
 {name:'Safe Life Defense Hyper Concealable',features:['HYPERLINE HL.HG2: manufacturer-listed NIJ IIIA','Flexible inserts in a brushed polyester carrier','Six comfort straps; twelve adjustment points'],dimensions:'Armor: 4.83 ± 0.25 mm • carrier: 0.76 mm',contribution:'Concealable soft ballistic torso coverage beneath the stab vest.',sources:[source('Safe Life Defense','https://safelifedefense.com/shop/hyper-concealable-vest/')]},
 {name:'PPSS-style carbon-composite panels',features:['Separate front, back and left-flank panels','Carbon-composite material reference','Custom panel layout; no rating assigned'],dimensions:'Custom geometry — see component bounds',contribution:'A separate rigid torso barrier over the soft vest.',sources:[source('PPSS','https://www.ppss-group.com/stab-vests/')]},
 {name:'Concealed neck lames',features:['Three overlapping curved lames','Covered by the Cutlon turtleneck','Open nape; independent of the torso'],dimensions:'35 mm lame height • custom geometry',contribution:'Concept throat coverage beneath the fabric collar.',sources:[source('Cutlon pocket fabric','https://cutlon.com/features/')]},
 {name:'Wraparound harness',features:['Continuous chest, rib and limb straps','Torso slots and separate sleeve mounts','No waist belt'],dimensions:'Torso webbing: 25 mm • limb loops: 18 mm',contribution:'Supports the shells while preserving movement between plates.',sources:[]},
 {name:'Custom plated outer shells',features:['Thin muscle-contoured polymer concept','Chrome Nanovate coating reference','Independent joints and four sliding abdominal lames'],dimensions:'Custom geometry — see component bounds',contribution:'A fitted outer shell over the protective inserts.',sources:[ng,source('Nanovate coating','https://www.integran.com/structural-hybrid-components')]},
 {name:'NETFORCE gloves / athletic boots',features:['Extended glove cuffs and mesh knuckle panels','Articulated fingers and flexible wrist transitions','Independent boots with concealed met guards'],dimensions:'Custom visual fit — see component bounds',contribution:'Hand coverage and footwear integration around the suit.',sources:[source('NETFORCE','https://netforce-defense.com/')]}
];
export const GHOST_PRODUCTS={
 chest:{name:'D3O Ghost Chest — full',features:['CE Level 1 • EN 1621-3:2018','Winged rib coverage and open triangular geometry','Lycra backing faces the body; removable pocket insert'],dimensions:'335 × 245 × 8.25 mm • published flat size',contribution:'Impact absorption across the chest and adjoining ribs.',sources:[chest]},
 back:{name:'D3O Ghost Back — M',features:['CE Level 1 • EN 1621-2:2014','Open lattice with a tapered lower extension','Fabric backing toward the body; external Cutlon pocket'],dimensions:'262 × 404 × 8 mm • published size M',contribution:'Flexible impact coverage along the back.',sources:[back]},
 shoulder:{name:'D3O Ghost L2 — shoulder',features:['CE Level 2 • EN 1621-1:2012, Type A','Tapered triangular cells on stretch fabric','Removable external Cutlon shoulder pocket'],dimensions:'193 × 154 × 11 mm • published flat size',contribution:'Impact absorption over the shoulder joint.',sources:[limb]},
 limb:{name:'D3O Ghost L2 — knee / elbow',features:['CE Level 2 • EN 1621-1:2012, Type A','Long tapered outline with articulation notches','Removable external Cutlon joint pocket'],dimensions:'240 × 147 × 11 mm • published flat size',contribution:'Impact coverage around the elbow or knee.',sources:[limb]},
 met:{name:'D3O Ghost Met Guard — LP M',features:['Segmented triangles conform over the instep','Fabric-backed insert in the Cutlon foot pocket','Performance depends on the complete boot construction'],dimensions:'134 × 108 × 6 mm • published LP size M',contribution:'Metatarsal impact protection over the top of the foot.',sources:[met]}
};
function modelDimensions(component){return component.dimensions?component.dimensions.map(v=>Math.round(v*1000)).join(' × ')+' mm • model bounds (W × H × D)':'Custom dimensions';}
export function componentProduct(component){
 const n=component.name.toLowerCase(),base=PRODUCTS[component.layer],ghost=component.meshes.find(m=>m.userData.ghostKind)?.userData.ghostKind;
 if(ghost){const product={...GHOST_PRODUCTS[ghost]};if(n.includes('elbow'))product.contribution='Impact absorption at the elbow, with the long insert following the arm.';if(n.includes('knee'))product.contribution='Impact absorption around the knee, with a tapered lower extension.';return product;}
 if(component.id==='hyperline')return {...PRODUCTS[2],dimensions:PRODUCTS[2].dimensions+'; '+modelDimensions(component)};
 if(component.id==='groin-cup')return {name:'Removable groin cup — concept',features:['Curved insert in a soft textile envelope','Separate from the abdominal plates','Custom, unrated component'],dimensions:modelDimensions(component),contribution:'Concept impact coverage at the groin without bridging the waist.',sources:[]};
 if(component.id==='groin-pouch'||component.id==='groin-support')return {name:'Floating groin carrier',features:['Flexible cut-resistant pouch','Internal harness tabs and soft leg loops','Removable insert; no waist belt'],dimensions:modelDimensions(component),contribution:'Holds the separate groin insert while allowing hip movement.',sources:[PRODUCTS[0].sources[0]]};
 if(component.layer===6&&/biceps|hamstring|forearm|thigh|shin/.test(n))return {name:'NG Ballistics material reference',features:['Custom body-following shell with rounded margins','Independent sleeve mount and dark inner substrate','Limb design and dimensions are custom; no rating assigned'],dimensions:modelDimensions(component),contribution:n.includes('hamstring')?'Adds rear-thigh shell coverage while leaving the knee crease free.':n.includes('biceps')?'Adds upper-arm shell coverage without joining the shoulder or elbow.':n.includes('thigh')?'Adds fitted shell coverage over the quadriceps.':n.includes('shin')?'Adds a contoured shell along the front of the lower leg.':'Adds a fitted outer-forearm shell with a flexible wrist transition.',sources:[ng]};
 if(component.layer===7&&n.includes('boot'))return {name:'Athletic boot — custom fit',features:['Closed heel and shaped traction sole','Cross laces and flexible ankle collar','D3O met insert housed beneath the upper'],dimensions:modelDimensions(component),contribution:'Footwear around the concealed instep protector.',sources:[met]};
 return {...base,dimensions:component.layer===0?modelDimensions(component):component.layer===5?base.dimensions:modelDimensions(component)};
}
